### ISSUE TITLE
SEO plugin is installed, but unavailable

### ISSUE THREAD

**Issue by joshwalsh** [ethercreative/seo#384]
### Description

Hello.  Out of the blue today I started receiving this error.   We've been using SEO without any issue for a long time, so I'm not sure what caused this.   Clicking the "Enable" button doesn't do anything (it's already enabled, and I've tried disabling and re-enabling it).  I'm afraid to uninstall it without losing our content (locally wouldn't be an issue).

![Screen Shot 2021-12-21 at 4 55 59 PM](https://user-images.githubusercontent.com/19155/147002833-1330fbb7-8a6a-4b8d-be22-98f23d166b6b.png)

![Screen Shot 2021-12-21 at 4 58 40 PM](https://user-images.githubusercontent.com/19155/147002877-1f9a7fc5-7178-42ae-a0ba-903aee41130d.png)

Any suggestions?

- Craft version: 3.7.26
- SEO version: 3.7.4
- PHP version: 7.4.12

**Comment by alexjcollins** [comment]
How strange! If you do have the site running locally, could you try deleting the vendor folder and `composer.lock` file and then try `composer update`?

**Comment by joshwalsh** [comment]
Hi Alex,

Yeah, strange.  I actually tried that before opening this ticket (and again just now).  I've also tried backing out to an older version of SEO, but has the same effect.

I have isolated the problem to be something within my specific field.  I was able to create a new SEO field, remove the old one from the section, and the new field works just fine.   So, I must have data out of whack somewhere on that specific field.  If I reverse that change (take off my test field and put my original one back) the error comes back.

Is it possible something is out of sync in my project.yaml definition of this field?   Below is the contents of my `config\project\fields\pageSeo--[hash].yaml`

Notice the error message in settings here matches what I see on screen, and is classified as a `type: craft\fields\MissingField`

```
contentColumnType: string
fieldGroup: 31f2e552-78d6-4e12-af62-bd6c0e8fcfa2 # Common
handle: pageSeo
instructions: ''
name: 'Page SEO'
searchable: false
settings:
  errorMessage: 'Component class ''ether\seo\fields\SeoField'' belongs to an uninstalled plugin (SEO).'
  expectedType: ether\seo\fields\SeoField
  settings: '{"description":"","hideSocial":"","robots":["","","","","",""],"socialImage":"","suffixAsPrefix":null,"title":[{"key":"1","locked":"0","template":"{title}"},{"key":"2","locked":"1","template":" - {{ siteName }}"}],"titleSuffix":null}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
```
